### PR TITLE
fix(report): Result field is optional.

### LINKED ISSUE #212: 1.11.0-rc1 Panic: runtime error: invalid memory address or nil pointer dereference
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Running policies:
```bash
k get clusteradmissionpolicies.policies.kubewarden.io                                                                                                0.006s
NAME                        POLICY SERVER   MUTATING   BACKGROUNDAUDIT   MODE      OBSERVED MODE   STATUS   AGE
psa-label-enforcer-policy   default         true       true              protect   protect         active   9m2s
privileged-pods             default         false      true              protect   protect         active   9m44s
safe-labels                 default         false      true              protect   protect         active   8m19s
```

Error:
```
{"level":"debug","ca-cert-file":"/pki/policy-server-root-ca-pem","time":"2024-03-01T12:03:15Z","message":"appended cert file to in-app RootCAs trust store"}
{"level":"info","time":"2024-03-01T12:03:15Z","message":"clusterwide resources scan started"}
{"level":"info","dict":{"policies to evaluate":2,"policies skipped":0},"time":"2024-03-01T12:03:15Z","message":"cluster admission policies count"}
{"level":"debug","response":{"uid":"7e8491fa-c84e-4e55-aad0-45c0dde2ddf2","allowed":true,"policy":"psa-label-enforcer-policy","resource":"kube-system"},"time":"2024-03-01T12:03:15Z","message":"audit review response"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x68 pc=0x15d144f]

goroutine 1 [running]:
github.com/kubewarden/audit-scanner/internal/report.newPolicyReportResult({0x1c8a0d8, 0xc000478200}, 0xc00036d440, 0x0, {0xc000250ee0?, 0x0?})
	/workspace/internal/report/report.go:136 +0x8f
github.com/kubewarden/audit-scanner/internal/report.AddResultToClusterPolicyReport(0xc0006d0580, {0x1c8a0d8, 0xc000478200}, 0xc000250ee0?, 0xb?)
	/workspace/internal/report/report.go:114 +0x9a
github.com/kubewarden/audit-scanner/internal/scanner.(*Scanner).auditClusterResource(0xc0006b8370, {0x1c73cc0, 0x295a5e0}, {0xc0002b87c0, 0x2, 0xc000279660?}, {0xc00051e090})
	/workspace/internal/scanner/scanner.go:309 +0x4f3
github.com/kubewarden/audit-scanner/internal/scanner.(*Scanner).ScanClusterWideResources.func1({0x1c60a30?, 0xc000132f40?})
	/workspace/internal/scanner/scanner.go:198 +0x4b
k8s.io/apimachinery/pkg/apis/meta/v1/unstructured.(*UnstructuredList).EachListItem(0xc0002865c0, 0xc00041c8a0)
	/go/pkg/mod/k8s.io/apimachinery@v0.29.2/pkg/apis/meta/v1/unstructured/unstructured_list.go:48 +0x6d
k8s.io/apimachinery/pkg/api/meta.eachListItem({0x1c609e0?, 0xc0002865c0}, 0xc00041c8a0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.29.2/pkg/api/meta/help.go:136 +0x9c
k8s.io/apimachinery/pkg/api/meta.EachListItem(...)
	/go/pkg/mod/k8s.io/apimachinery@v0.29.2/pkg/api/meta/help.go:119
k8s.io/client-go/tools/pager.(*ListPager).EachListItem.func1({0x1c609e0?, 0xc0002865c0?})
	/go/pkg/mod/k8s.io/client-go@v0.29.2/tools/pager/pager.go:185 +0x25
k8s.io/client-go/tools/pager.(*ListPager).eachListChunkBuffered(0xc0000cc468, {0x1c73cc0, 0x295a5e0}, {{{0x0, 0x0}, {0x0, 0x0}}, {0x0, 0x0}, {0x0, ...}, ...}, ...)
	/go/pkg/mod/k8s.io/client-go@v0.29.2/tools/pager/pager.go:245 +0x2bb
k8s.io/client-go/tools/pager.(*ListPager).EachListItem(0xc00025ba60?, {0x1c73cc0?, 0x295a5e0?}, {{{0x0, 0x0}, {0x0, 0x0}}, {0x0, 0x0}, {0x0, ...}, ...}, ...)
	/go/pkg/mod/k8s.io/client-go@v0.29.2/tools/pager/pager.go:184 +0x85
github.com/kubewarden/audit-scanner/internal/scanner.(*Scanner).ScanClusterWideResources(0xc0006b8370, {0x1c73cc0?, 0x295a5e0})
	/workspace/internal/scanner/scanner.go:192 +0x466
github.com/kubewarden/audit-scanner/cmd.startScanner({0x0?, 0xc0000fb180?}, 0x10?, 0x0?)
	/workspace/cmd/root.go:125 +0x9b
github.com/kubewarden/audit-scanner/cmd.glob..func1(0xc0001b8b00?, {0x19f7fae?, 0x4?, 0x19f7f76?})
	/workspace/cmd/root.go:92 +0x477
github.com/spf13/cobra.(*Command).execute(0x29156a0, {0xc000134010, 0x52, 0x57})
	/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:983 +0xabc
github.com/spf13/cobra.(*Command).ExecuteC(0x29156a0)
	/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/kubewarden/audit-scanner/cmd.Execute()
	/workspace/cmd/root.go:103 +0x36
main.main()
	/workspace/main.go:8 +0xf
```

### To reproduce:

```bash
# resources/default-kubewarden-controller-values.yaml
telemetry:
  enabled: false
policyServer:
  env:
    - name: KUBEWARDEN_LOG_LEVEL
      value: debug
auditScanner:
  enable: true
  image:
    tag: v1.11.0-rc1
image:
  tag: v1.11.0-rc1


# resources/default-kubewarden-defaults-values.yaml
recommendedPolicies:
  enabled: False
policyServer:
  replicaCount: 1
  image:
    tag: v1.11.0-rc1

# remove --store from controller chart
helm pull --repo https://charts.kubewarden.io/ kubewarden-controller --untar
sed -i '/store/d' ~/kubewarden-controller/templates/_helpers.tpl.txt

# Change Makefile to use local chart
-               $(KUBEWARDEN_CONTROLLER_CHART_RELEASE) $(KUBEWARDEN_CHARTS_LOCATION)/kubewarden-controller
+               $(KUBEWARDEN_CONTROLLER_CHART_RELEASE) ./kubewarden-controller


# Open tests/audit-scanner.bats
# comment out teardown function

# Run tests
make clean cluster install audit-scanner.bats
kubectl create job  --from=cronjob/audit-scanner testing  --namespace kubewarden
kubectl get pods -n kubewarden
```

### PR DESCRIPTION
**Pull request by jvanz**
## Description

The code which builds the PolicyReportResult does check if the Result field from the AdmissionRespose type is nil. Causing a nil pointer dereference. This field is optional and it can be nil. Specially if the policy result is "allowed" where there is not further details about the result of the evaluation.

This commit fixes this issue by checking if the Result field has something before trying to get the possible error message from the policy.

Fix #212 

## Test

I've added a new unit test to cover this bug.

```shell
make unit-tests
```

### CODE REVIEW

File: internal/report/report_test.go [hunk 1]
```diff
@@ -235,6 +235,46 @@ func TestNewPolicyReportResult(t *testing.T) {
 				},
 			},
 		},
+		{
+			name: "Validating policy, allowed response with no message",
```
Comment (fabriziosestito) [inline internal/report/report_test.go:239]: Instead adding a new test we should modify existing tests in this file and the mock policy server handler in `scanner_test.go` to remove the Result when the `AdmissionReview` is allowed

**Review by fabriziosestito — CHANGES_REQUESTED** [review]

File: internal/report/report_test.go (hunk 1 above)
Comment (jvanz) [reply internal/report/report_test.go]: Yeah, I was thinking about that too. But I've decided to keep the old tests just in case I was missing something that you know. As you are not around and leave that for the review process, like know. :)

I've just updated the tests. Please, give another look.

**Review by fabriziosestito — APPROVED** [review]
